### PR TITLE
Resolves 2118: Fix some cases in mor examples

### LINKED ISSUE #2118: Fix and document how to run cases in mor/examples
- [ ] linear elasticity 3d
- [ ] thermal building 
- [ ] geoheatdiffusion

### PR DESCRIPTION
**Pull request by lberti**
Fix compilation and execution of some MOR examples:
- convection (room, cabin, cavity)
- stokesDEIM
- greplDEIM
- heat1d
- heat2d
- geoheatdiffusion

closes #2118

### CODE REVIEW

File: mor/mor/feel/feelmor/crb.hpp [hunk 1]
```diff
@@ -2573,14 +2605,20 @@ CRB<TruthModelType>::offline()
...
             std::string functionSpaceFilename = (M_elements_database.dbLocalPath() / fs::path(functionSpaceFilenameBase)).string();
             if( this->worldComm().isMasterRank() )
                 std::cout << "save Function Space : " << functionSpaceFilename << std::endl;
             M_model->rBFunctionSpace()->functionSpace()->save( functionSpaceFilename );
         }
+        else
+        {
+            mpl::range_c<int,0,space_type::nSpaces> keySpaces;
+            std::string localPath = M_elements_database.dbLocalPath().string();
+            boost::fusion::for_each( keySpaces, SaveCompositeFunctionSpace(localPath, this->name(), this->worldComm(), M_model ));
```
Comment (prudhomm) [inline mor/mor/feel/feelmor/crb.hpp:2620]: can we use boost hana instead of boost::fusion ?

**Review by prudhomm — APPROVED** [review]
