### PR TITLE
resolves 2391 : Implement setConfigFiles method for handling multiple configuration f…

### LINKED ISSUE #2391: Add multi-config Environment support
Multiple Feel++ configuration files should be loaded in the order supplied so that the most recent file wins when duplicate options are present. Regression coverage is missing in both the C++ testsuite and the Python bindings.

### PR DESCRIPTION
**Pull request by prudhomm**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/feelpp/feelpp/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes?
- [x] Have you successfully run the Feel++ testsuite with your changes locally?
- [ ] Have you written Doxygen comments in your contribution ?

-----

- closes #2391 

only=feelpp,testsuite

### CODE REVIEW

**Review by vincentchabannes — APPROVED** [review]

File: feelpp/feel/feelalg/preconditionerpetsc.cpp [hunk 1]
```diff
@@ -652,12 +652,36 @@ ConfigurePC::run( PC& pc )
 {
     VLOG(2) << "configuring PC... (sub: " << this->sub() << ")";
     //PCSetOptionsPrefix( pc, (this->prefix()+"_").c_str());
+#if !defined(FEELPP_HAS_SPDLOG)
```
Comment (vincentchabannes) [inline feelpp/feel/feelalg/preconditionerpetsc.cpp:655]: SPDLOG dependency is required, no? All #if #endif can be removed?

**Review by vincentchabannes — APPROVED** [review]
